# Generated by Django 4.2.16 on 2026-05-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_course_student_proctoringevent_attempt_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='block_tab_switch',
            field=models.BooleanField(default=False),
        ),
    ]
