# Generated by Django 6.0.5 on 2026-05-06 01:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def deduplicate_in_progress_attempts(apps, schema_editor):
    """Keep only the most recent IN_PROGRESS attempt per (user, exam) pair."""
    Attempt = apps.get_model('exams', 'Attempt')
    seen = {}
    for attempt in Attempt.objects.filter(status='IN_PROGRESS').order_by('started_at'):
        key = (str(attempt.user_id), str(attempt.exam_id))
        if key in seen:
            # Mark the older duplicate as ABANDONED
            Attempt.objects.filter(id=seen[key]).update(status='ABANDONED')
        seen[key] = attempt.id


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_user_notification_prefs_integration_exam_course'),
    ]

    operations = [
        migrations.RunPython(deduplicate_in_progress_attempts, migrations.RunPython.noop),

        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('questions_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('passing_threshold', models.PositiveSmallIntegerField(default=60, help_text='Percentage 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_default', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userintegration',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['exam', 'status'], name='attempt_exam_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(
                condition=models.Q(status='IN_PROGRESS', student__isnull=True),
                fields=('user', 'exam'),
                name='unique_in_progress_user_attempt',
            ),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(
                condition=models.Q(status='IN_PROGRESS'),
                fields=('student', 'exam'),
                name='unique_in_progress_student_attempt',
            ),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question_id'), name='unique_attempt_answer'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_course_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'question'), name='unique_exam_question'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('course', 'code'), name='unique_student_code_per_course'),
        ),
        migrations.AddConstraint(
            model_name='userintegration',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_user_integration'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_templates', to='exams.organization'),
        ),
        migrations.AddConstraint(
            model_name='examtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_template_name_per_org'),
        ),
    ]
