# Generated by Django 6.0.5 on 2026-05-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_fix_attempt_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='extra_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
