# Generated by Django 4.2.16 on 2026-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_importjob_draft_token'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'unique_student_code_per_org'
                ) THEN
                    ALTER TABLE exams_student
                    ADD CONSTRAINT unique_student_code_per_org
                    UNIQUE (organization_id, code);
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE exams_student
            DROP CONSTRAINT IF EXISTS unique_student_code_per_org;
            """,
            state_operations=[
                migrations.AddConstraint(
                    model_name='student',
                    constraint=models.UniqueConstraint(
                        fields=('organization', 'code'),
                        name='unique_student_code_per_org',
                    ),
                ),
            ],
        ),
    ]
